language: python
python:
  - 3.2
  - 2.7
  - 2.6
install:
  - pip install nose
  - pip install Cython
  - if python --version 2>&1 | grep -v "Python 3." >/dev/null; then pip install unittest2 ; fi
  - python setup.py install
script:
  - nosetests traits --exe
notifications:
  email:
    - hack@delley.net
