language: python
python:
  - 2.6
  - 2.7
  - "2.7_with_system_site_packages"
  - 3.2
  - "3.2_with_system_site_packages"
  - 3.3
  - 3.4
before_install:
  # On Python 2.7 we install PyQt4 and run the UI tests.
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then source .travis_before_install; fi
install:
  - pip install nose
  - if ! [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; then pip install unittest2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION > '3.' ]]; then pip install numpy ; fi
  - pip install cython
  - pip install coverage
  - pip install coveralls
  - python setup.py install
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner/
  - cd testrunner
script:
  - coverage run -m nose.core traits --exe
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
