build: false
shallow_clone: true
environment:

  matrix:
    - python: "C:/Python35-x64"

    - python: "C:/Python36-x64"

cache:
  - c:\egg_cache

init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path
install:
  - ps: if ((Test-Path "c:/egg_cache") -eq 0) { mkdir c:/egg_cache }
  - ps: python -m pip install --upgrade --no-binary wheel pip
  - ps: pip install --upgrade wheel
  - ps: pip --version
  - cmd /v:on /e:on /c ".\appveyor-install.cmd"
test_script:
  - cmd /v:on /e:on /c ".\appveyor-test.cmd"
